### ISSUE TITLE
Function for controlling DTR, etc

### ISSUE THREAD

**Issue by magthe** [jmct/serial#1]
I just ran into a device that requires me to set _DTR_ to _false_ in order for it to work properly (a Brainboxes US-324 USB to RS-485 adapter). It would be lovely to have a function for setting _DTR_ in _serial_.

**Comment by jmct** [comment]
Hey @magthe,

How much of a priority is this for you? I'll happily look at it in the next few weeks, but if it's important I'll get on it right away.

Cheers

**Comment by magthe** [comment]
The sooner the better, of course. I can do without it for a while though, so there's no hurry :)

My looking into this suggests that the only way to achieve this is using _ioctl_, which is rather unportable. I'm completely new to the area of serial port programming on Unix though (and completely blown away by the immense complexity) so I might have gotten that wrong. Do you know if it's correct that one has to resort to _ioctl_ calls for this?

(Basically I was looking for a quick way to get a hack in place prior to _serial_ having a more proper solution.)
